import { sources,activeSubjects,activeTopics,activeGroups,displaySubjectName } from './curriculum.mjs';
import { today,dateKey,addDays,dayDiff,uid,createState,progressFor,setLevel,dueTopics,reviewTopic,completeTask,streak,phases,validateState,validateTimer,topicById,subjectById,activityDates,loadRecords,taskInCurriculum,politicsMode,timeBudget,countdown,reconcileSettings,needsOnboarding,commitRecords,evaluatePlan,monday,draftStale,RECORD_KEY,BACKUP_LIMIT } from './core.mjs';
const APP_VERSION='1.0.5',KEY=RECORD_KEY,TIMER_KEY='qingzhou.timer.v4';
const $=(q,root=document)=>root.querySelector(q);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths = {
  grid: '<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
  book: '<path d="M12 5v16m0-16C9 3 5 3 2 4v15c3-1 7-1 10 2 3-3 7-3 10-2V4c-3-1-7-1-10 1Z"/>',
  calendar: '<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M16 3v4M8 3v4M3 11h18M8 15h2m4 0h2m-8 3h2"/>',
  repeat: '<path d="m17 2 4 4-4 4M3 11V9a3 3 0 0 1 3-3h15M7 22l-4-4 4-4m14-1v2a3 3 0 0 1-3 3H3"/>',
  chart: '<path d="M3 3v18h18M7 16v-5m5 5V7m5 9v-8"/>',
  clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
  settings: '<path d="m10 3-.7 2.2-2 .9L5 5.6 3 9l1.7 1.8v2.4L3 15l2 3.4 2.3-.5 2 .9L10 21h4l.7-2.2 2-.9 2.3.5 2-3.4-1.7-1.8v-2.4L21 9l-2-3.4-2.3.5-2-.9L14 3Z"/><circle cx="12" cy="12" r="3"/>',
  search: '<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4.5 4.5"/>',
  arrow: '<path d="M4 12h16m-6-6 6 6-6 6"/>',
  chevron: '<path d="m9 5 7 7-7 7"/>',
  down: '<path d="m6 9 6 6 6-6"/>',
  plus: '<path d="M12 5v14M5 12h14"/>',
  check: '<path d="m5 12 4 4L19 6"/>',
  close: '<path d="m6 6 12 12M6 18 18 6"/>',
  play: '<path d="m8 4 12 8-12 8Z"/>',
  pause: '<path d="M8 5v14M16 5v14"/>',
  reset: '<path d="M3 10a9 9 0 1 1 2 9M3 3v7h7"/>',
  flame: '<path d="M12 2c1 5-3 6-3 10-2-1-3-3-3-3-5 8 0 13 6 13s11-7 6-13c0 4-3 4-3 4 2-5-1-8-3-11Z"/>',
  leaf: '<path d="M20 3C7 1 1 9 6 16s16 0 14-13ZM4 21 15 10"/>',
  target: '<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',
  download: '<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',
  upload: '<path d="M12 15V3m-5 5 5-5 5 5M4 16v5h16v-5"/>',
  spark: '<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5ZM20 2v4m-2-2h4"/>',
  trash: '<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7"/>',
  info: '<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/>',
  menu: '<path d="M4 6h16M4 12h16M4 18h16"/>',
  route: '<circle cx="6" cy="5" r="2"/><circle cx="18" cy="19" r="2"/><path d="M6 7v9a3 3 0 0 0 3 3h3m6-2V8a3 3 0 0 0-3-3h-3"/>'
};
const icon = (name, cls = '') => `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.book}</svg>`;
const btn = (action, text, cls = 'btn', extra = '') => `<button type="button" class="${cls}" data-action="${action}" ${extra}>${text}</button>`;
const levels = ['未开始', '学习中', '已学过', '已掌握'];

let storageError='',state;
try{state=loadRecords(localStorage).state;}catch(e){state=createState();storageError='新版记录损坏或不可读。原始数据未覆盖，请导出原始记录或导入有效的 v4 备份。';}
let savedState=structuredClone(state),timer=null;
try{timer=validateTimer(JSON.parse(localStorage.getItem(TIMER_KEY)||'null'));}catch{}
let page='dashboard',filter='all',selectedSubject='math',selectedDate=today(),weekStart=monday(today()),chartRange=7,knowledgeQuery='',expanded=new Set(),focusDuration=25,focusSubject='math';
let draft=state.draft?{candidate:{...state,tasks:state.draft.tasks,adjustments:state.draft.adjustments},start:state.draft.week,end:addDays(state.draft.week,6)}:null;
let guideState=createState(),onboardingSettings={...guideState.settings},onboardingStep='subjects';
let modal=null,modalStack=[],returnFocus=null,toastTimeout,lastDate=today(),undoIds=[];
let modalContent='',modalOptions={},pageValues={},fieldError='';
const navItems=[['dashboard','grid','首页'],['knowledge','book','学习内容'],['plan','calendar','学习计划'],['review','repeat','复习查漏'],['analytics','chart','学习统计'],['focus','clock','专注空间'],['settings','settings','设置']];
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.classList.remove('visible'),4500);}
function save(candidate=state){try{state=commitRecords(localStorage,candidate);savedState=structuredClone(state);fieldError='';syncDraft();return true;}catch(e){state=structuredClone(savedState);fieldError='保存失败：'+e.message+' 输入与原记录保留，请重试。';const area=$('.save-error')||document.createElement('p');area.className='save-error';area.setAttribute('role','alert');area.textContent=fieldError;if(!area.isConnected)($('#modal-root form')||$('#main form')||$('#main')).prepend(area);toast(fieldError);return false;}}
function syncDraft(){draft=state.draft?{candidate:{...state,tasks:state.draft.tasks,adjustments:state.draft.adjustments},start:state.draft.week,end:addDays(state.draft.week,6)}:null;}
function transact(command){const prior=structuredClone(state);try{const result=evaluatePlan(state,{command});if(save(result.state)){const added=state.adjustments.filter(a=>!prior.adjustments.some(x=>x.id===a.id)&&a.type!=='missed');undoIds.push(...added.map(a=>a.id));render();return true;}}catch(e){toast(e.message);}return false;}
function dataNow(){return needsOnboarding(state)?guideState:state;}
function currentSubjects(){return activeSubjects(state.settings);}
function currentTopics(){return activeTopics(state.settings);}
function currentGroups(){return activeGroups(state.settings);}
function groupTopics(id){return currentTopics().filter(t=>subjectById[t.subject].group===id);}
function plannedTasks(date){return state.tasks.filter(t=>t.date===date&&!t.queued&&!t.suspended&&(t.done||taskInCurriculum(t,state.settings)));}
function taskSubjectName(t){return displaySubjectName(subjectById[t.subject],state.settings);}
function examLabel(){return '数学'+(state.settings.mathExam==='math1'?'一':'二')+' · 英语'+(state.settings.englishExam==='english1'?'一':'二')+' · 408';}
function currentTrackForSubject(id){const g=subjectById[id]?.group;return g==='math'?state.settings.mathExam:g==='english'?state.settings.englishExam:undefined;}
function noticesView(){return '';}
function minutesText(n) { return n >= 60 ? `${(n / 60).toFixed(n % 60 ? 1 : 0)} 小时` : `${Math.round(n * 10) / 10} 分钟`; }
function niceDate(key, opts = { month: 'long', day: 'numeric' }) { return new Date(`${key}T12:00:00`).toLocaleDateString('zh-CN', opts); }
function actualMinutes(date) { return state.sessions.filter(s => s.date === date).reduce((n, s) => n + s.minutes, 0); }
function progressBar(value, color = 'var(--green)') { return `<div class="progress-track" role="progressbar" aria-label="掌握进度" aria-valuenow="${value}" aria-valuemin="0" aria-valuemax="100"><span style="width:${value}%;background:${color}"></span></div>`; }
function circle(value, size = 60, color = 'var(--green)') { return `<div class="ring" style="--p:${value};--ring-color:${color};width:${size}px;height:${size}px"><span>${value}<small>%</small></span></div>`; }

function pageHeading(kicker, title, subtitle, action = '') { return `<div class="page-heading"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`; }
function dailyQuote() {
  const lines=['今天先完成眼前这一步。','把目标拆小，把行动做实。','不必等状态完美，先给自己一段专注。','每次认真回顾，都在让知识更牢靠。','计划可以调整，努力可以继续。','少一点犹豫，多一个完成的小目标。','轻舟向前，每一步都留下痕迹。'];
  return lines[Math.abs(dayDiff('2026-01-01',today()))%lines.length];
}
function dashboardView() {
  const tasks=plannedTasks(today()), next=tasks.find(t=>!t.done), active=currentTopics(), done=tasks.filter(t=>t.done).length;
  const percent=progressFor(state,active), mins=actualMinutes(today()), remaining=countdown(state.settings);
  const metrics=[['knowledge','整体掌握进度',percent,'%',`已掌握 ${active.filter(t=>state.progress[t.id]?.level===3).length} / ${active.length} 个知识点`,'route'],['focus','今日专注',(mins/60).toFixed(1),'小时','按实际计时统计','clock'],['today-plan','今日任务',done,`/ ${tasks.length}`,`还有 ${tasks.length-done} 项未完成`,'check'],['learning-heatmap','连续学习',streak(state),'天','查看学习足迹','flame']];
  return `${pageHeading('YOUR STUDY DESK',`${esc(state.settings.name)}，今天从这里开始。`,`${examLabel()} · 每日 ${state.settings.dailyHours} 小时`,btn('settings','学习设置','btn btn-white'))}
  <section class="start-panel"><div class="start-copy"><span class="eyebrow">${timer?'当前专注':'接下来学什么'}</span><h2>${timer?'继续当前这段专注':next?esc(next.title):'为今天选一个小目标'}</h2><p>${timer?esc(taskSubjectName(timer)):next?`${esc(taskSubjectName(next))} · 预计 ${minutesText(next.minutes)}`:'生成可修改的 本周计划，或直接开始一段专注。'}</p><div class="button-row">${btn('start-today',`${icon('play')} ${timer?'返回当前专注':'开始学习'}`,'btn btn-primary btn-large')}${btn('plan',`${icon('calendar')} 查看计划`,'btn btn-white')}</div></div><div class="compact-countdown"><span>${remaining.label}</span><strong>${remaining.days}<small>天</small></strong><span>${esc(state.settings.examDate)} · 可调整</span><span>目标 ${state.settings.target} 分</span></div></section>
  <div class="section-heading"><h2>学习内容</h2>${btn('knowledge',`全部知识点 ${icon('arrow')}`,'text-btn')}</div>
  <section class="subject-grid">${currentGroups().map(g=>{const list=groupTopics(g.id),p=progressFor(state,list),count=list.filter(t=>(state.progress[t.id]?.level||0)>=2).length;return `<button class="subject-card" data-action="group" data-id="${g.id}" style="--subject:${g.color};--subject-light:${g.light}"><div class="subject-card-top"><div class="subject-symbol">${g.symbol}</div><span>${g.score} 分 ${icon('chevron')}</span></div><h3>${g.name}</h3><p>${g.description}</p><div class="subject-progress"><span>掌握进度</span><strong>${p}%</strong></div>${progressBar(p,g.color)}<div class="subject-bottom">已学 ${count} / ${list.length} 个知识点</div></button>`;}).join('')}</section>
  <section class="metrics dashboard-metrics">${metrics.map(([action,label,value,unit,foot,i])=>`<button class="metric metric-link" data-action="${action}"><span class="metric-label">${label}${icon(i)}</span><span class="metric-value">${value}<small>${unit}</small></span><span class="metric-foot">${foot}${icon('chevron')}</span></button>`).join('')}</section>
  <div class="quote-strip motivational-content">${icon('leaf')}<span>${dailyQuote()}</span></div>
  <div class="dashboard-bottom"><section class="panel today-panel"><div class="panel-heading"><h2>今日计划</h2>${btn('today-plan','查看全部','text-btn')}</div>${tasks.length?tasks.slice(0,4).map(taskRow).join(''):emptyState('今天还没有确认计划','到计划页选择想学的内容。',btn('plan','安排学习','btn btn-primary'))}</section><section class="panel rhythm-panel"><div class="panel-heading"><h2>近 7 天学习节奏</h2></div>${barChart(7)}</section></div>`;
}

function barChart(days, compact = false) {
  const data = Array.from({ length: days }, (_, i) => { const date = addDays(today(), i - days + 1); return { date, value: actualMinutes(date) / 60 }; });
  const max = Math.max(state.settings.dailyHours, ...data.map(d => d.value), 1);
  return `<div class="bar-chart ${compact ? 'compact' : ''}"><div class="chart-y"><span>${Math.ceil(max)}h</span><span>${Math.ceil(max / 2)}h</span><span>0h</span></div><div class="chart-plot"><div class="chart-grid-lines"><i></i><i></i><i></i></div><div class="chart-bars">${data.map((d, i) => `<div class="chart-column" title="${d.date}：${d.value.toFixed(1)} 小时"><div class="bar-holder"><div class="chart-bar ${d.date === today() ? 'current' : ''} ${d.value === 0 ? 'zero' : ''}" style="height:${Math.max(3, d.value / max * 100)}%"><span>${d.value.toFixed(1)}h</span></div></div><span class="chart-x ${d.date === today() ? 'current' : ''}">${days > 7 ? (i % 5 === 0 || i === days - 1 ? d.date.slice(5).replace('-', '/') : '') : d.date === today() ? '今天' : ['日', '一', '二', '三', '四', '五', '六'][new Date(`${d.date}T12:00:00`).getDay()]}</span></div>`).join('')}</div></div></div>`;
}
function emptyState(title, text, action = '') { return `<div class="empty-state"><div class="empty-icon">${icon('leaf')}</div><h3>${title}</h3><p>${text}</p>${action}</div>`; }
function knowledgeView() {
  const allSubjects = currentSubjects(), allTopics = currentTopics(), allGroups = currentGroups();
  const visible = allSubjects.filter(s => filter === 'all' || s.group === filter);
  if (!visible.some(s => s.id === selectedSubject)) selectedSubject = visible[0].id;
  const s = visible.find(x => x.id === selectedSubject), list = s.chapters.flatMap(c => c.topics), matched = knowledgeQuery ? allTopics.filter(t => (filter === 'all' || subjectById[t.subject].group === filter) && t.title.toLowerCase().includes(knowledgeQuery.toLowerCase())) : null;
  return `${pageHeading('YOUR KNOWLEDGE, CONNECTED', '让知识，长成体系。', `${allSubjects.length} 门学科 · ${allTopics.length} 个知识点，从理解到掌握，每一步都留下记录。`, btn('method', `${icon('info')} 如何记录进度`, 'btn btn-white'))}
  <div class="filter-toolbar"><div class="filter-tabs">${[{ id: 'all', name: '全部科目' }, ...allGroups].map(g => btn('filter', g.name, `filter-tab ${filter === g.id ? 'active' : ''}`, `data-id="${g.id}"`)).join('')}</div><div class="inline-search">${icon('search')}<input id="knowledge-search" placeholder="查找知识点…" aria-label="查找知识点" value="${esc(knowledgeQuery)}"></div></div>
  ${matched ? `<section class="panel search-results"><div class="panel-heading"><h2>搜索结果</h2><span>${matched.length} 个知识点</span></div>${matched.length ? matched.map(topicRow).join('') : emptyState('没有找到匹配的知识点', '试试“极限”“进程”“阅读”等关键词。')}</section>` : `<div class="knowledge-layout"><aside class="subject-menu">${visible.map(x => { const ts = x.chapters.flatMap(c => c.topics); return `<button class="subject-menu-item ${x.id === s.id ? 'active' : ''}" data-action="subject" data-id="${x.id}"><span class="mini-symbol" style="color:${x.color}">${x.symbol}</span><div><strong>${displaySubjectName(x, state.settings)}</strong><span>${ts.length} 个知识点 · ${progressFor(state, ts)}%</span></div>${icon('chevron')}</button>`; }).join('')}<div class="study-hint">${icon('spark')}<strong>学会，比学完更重要</strong><p>试着合上书解释一遍，再独立完成一道题。</p></div></aside><section class="knowledge-main"><div class="panel subject-intro"><div><div class="eyebrow">${allGroups.find(g => g.id === s.group).name} / 学科路线</div><h2>${displaySubjectName(s, state.settings)}</h2><p>${s.description}</p></div>${circle(progressFor(state, list), 76, s.color)}<div class="method-tip">${icon('spark')}<span>${s.method}</span></div></div>${s.chapters.map((c, i) => { const open = expanded.has(c.id) || (!expanded.size && i === 0); const learned = c.topics.filter(t => state.progress[t.id]?.level >= 2).length; return `<section class="panel chapter"><button class="chapter-header" data-action="chapter" data-id="${c.id}" aria-expanded="${open}"><span class="chapter-number">${String(i + 1).padStart(2, '0')}</span><div><h3>${c.title}</h3><span>${learned} / ${c.topics.length} 已学 · ${progressFor(state, c.topics)}% 掌握</span></div><div class="chapter-progress">${progressBar(progressFor(state, c.topics), s.color)}</div>${icon(open ? 'down' : 'chevron')}</button>${open ? `<div class="chapter-content"><p class="chapter-goal">学习目标：${c.goal}</p>${c.topics.map(topicRow).join('')}</div>` : ''}</section>`; }).join('')}</section></div>`}
  <p class="content-note">这是可执行的复习目录，范围请对照报考年度大纲与院校要求。当前选择：${examLabel()}。</p>`;
}
function topicRow(t) { const level = state.progress[t.id]?.level || 0; return `<div class="topic-row"><span class="topic-dot level-${level}">${level === 3 ? icon('check') : ''}</span><button class="topic-title" data-action="topic" data-id="${t.id}">${esc(t.title)}${state.notes[t.id] ? '<span class="note-dot">有笔记</span>' : ''}${state.weakPoints[t.id] ? '<span class="weak-dot">待加强</span>' : ''}</button><button class="level-pill level-${level}" data-action="cycle-level" data-id="${t.id}" title="点击切换学习状态" aria-label="${esc(t.title)}，当前${levels[level]}，点击切换">${levels[level]}</button>${btn('topic', icon('chevron'), 'icon-btn', `data-id="${t.id}" aria-label="查看${esc(t.title)}详情"`)}</div>`; }
function reviewView() {
  const subjectById = Object.fromEntries(currentSubjects().map(s => [s.id, s]));
  const weakTopics=currentTopics().filter(t=>state.weakPoints[t.id]);
  const due = dueTopics(state), upcoming = currentTopics().filter(t => state.progress[t.id]?.nextReview > today()).sort((a, b) => state.progress[a.id].nextReview.localeCompare(state.progress[b.id].nextReview));
  return `${pageHeading('REMEMBER WHAT YOU LEARN', '让学过的，真正留下来。', '通过主动回忆与间隔复习，把短暂的理解变成长久的掌握。', `<span class="status-tag">${icon('repeat')} 1 · 3 · 7 · 14 · 30 天</span>`)}<div class="review-banner"><div>${icon('spark')}<h3>先回忆，再翻书</h3><p>试着独立复述概念、写出关键步骤，或重做一道典型题，再评估记忆情况。</p></div><div><strong>${due.length}</strong><span>个知识点待回顾</span></div></div><section class="panel"><div class="panel-heading"><h2>到期复习</h2><span class="small-muted">按最早到期排序</span></div>${due.length ? due.map(t => `<div class="review-row"><div class="review-subject" style="color:${subjectById[t.subject].color}">${icon('book')}</div><div class="review-body"><button data-action="topic" data-id="${t.id}">${t.title}</button><p>${subjectById[t.subject].name} · ${state.progress[t.id].nextReview === today() ? '今天到期' : `已到期 ${dayDiff(state.progress[t.id].nextReview, today())} 天`}</p></div><div class="button-row">${btn('review-again', '还不熟悉', 'btn btn-white', `data-id="${t.id}"`)}${btn('review-good', `${icon('check')} 能够回忆`, 'btn btn-primary', `data-id="${t.id}"`)}</div></div>`).join('') : emptyState('今天没有到期复习', '在知识地图将知识点标记为“已学过”，明天它就会出现在这里。', btn('knowledge', '去探索知识地图', 'btn btn-white'))}</section>${weakTopics.length?`<section class="panel"><h2>需要加强 · ${weakTopics.length}</h2>${weakTopics.map(t=>`<div class="upcoming-row"><button data-action="topic" data-id="${t.id}">${esc(t.title)}</button><span>${esc(state.weakPoints[t.id].reason||'待回访')}</span></div>`).join('')}</section>`:''}<section class="panel upcoming-panel"><div class="panel-heading"><h2>接下来的复习</h2><span class="small-muted">${upcoming.length} 项已安排</span></div>${upcoming.length ? upcoming.map(t => `<div class="upcoming-row"><span>${subjectById[t.subject].name}</span><button data-action="topic" data-id="${t.id}">${t.title}</button><strong>${niceDate(state.progress[t.id].nextReview)}</strong></div>`).join('') : '<p class="panel-empty-text">学过的知识会自动安排下一次复习，不用手动记住日期。</p>'}</section><p class="content-note">复习间隔是可执行的默认策略，并非对记忆效果的保证；“还不熟悉”会安排次日重学，“能够回忆”会逐步延长间隔。</p>`;
}
function analyticsView() {
  const subjects = currentSubjects();
  const total = state.sessions.reduce((n, s) => n + s.minutes, 0), dates = activityDates(state), mastered = currentTopics().filter(t => state.progress[t.id]?.level === 3).length;
  return `${pageHeading('SMALL EFFORTS ADD UP', '你的努力，自有回响。', '用真实记录看见变化，也为下一步找到方向。', btn('export', `${icon('download')} 导出学习记录`, 'btn btn-white'))}<section class="metrics analytics-metrics">${[['累计专注', (total / 60).toFixed(1), '小时', 'clock'], ['学习足迹', dates.size, '天', 'calendar'], ['完成任务', state.tasks.filter(t => t.done).length, '项', 'check'], ['掌握知识', mastered, '个', 'book']].map(([label, n, unit, i]) => `<div class="metric"><div class="metric-label">${label}${icon(i)}</div><div class="metric-value">${n}<small>${unit}</small></div></div>`).join('')}</section><section class="panel analytics-chart"><div class="panel-heading"><h2>专注时长趋势</h2><div class="segmented">${[7, 30].map(n => btn('chart-range', `近 ${n} 天`, chartRange === n ? 'active' : '', `data-id="${n}"`)).join('')}</div></div>${barChart(chartRange)}</section><div class="analytics-columns"><section class="panel"><div class="panel-heading"><h2>各科掌握情况</h2><span class="small-muted">按知识点状态计算</span></div>${subjects.map(s => { const p = progressFor(state, s.chapters.flatMap(c => c.topics)); return `<div class="mastery-row"><div><span>${s.name}</span><strong>${p}%</strong></div>${progressBar(p, s.color)}</div>`; }).join('')}</section><section class="panel"><div class="panel-heading"><h2>近 90 天的坚持</h2>${icon('leaf')}</div><div class="heatmap">${Array.from({ length: 91 }, (_, i) => { const date = addDays(today(), i - 90), m = actualMinutes(date), count = state.tasks.filter(t => t.done && (t.completedAt || t.date) === date).length, intensity = m >= 180 ? 4 : m >= 90 ? 3 : m > 0 ? 2 : count > 0 ? 1 : 0; return `<div class="heat-cell heat-${intensity}" title="${date}：专注 ${Math.round(m)} 分钟，完成 ${count} 项任务"></div>`; }).join('')}</div><div class="heat-legend"><span>${niceDate(addDays(today(), -90))} — 今天</span><span>少 <i class="heat-0"></i><i class="heat-1"></i><i class="heat-2"></i><i class="heat-3"></i><i class="heat-4"></i> 多</span></div><div class="stats-insight">${icon('spark')}<div><strong>${dates.size ? `已经积累了 ${dates.size} 天学习足迹` : '你的学习故事，从今天开始'}</strong><p>专注计时或完成一项任务，就会点亮当天的格子。没有学习的日子，也可以是蓄力的日子。</p></div></div></section></div>`;
}
function focusView() {
  const subjects = currentSubjects();
  if (timer && !subjects.some(s => s.id === timer.subject)) subjects.unshift(subjectById[timer.subject]);
  const selected = timer?.subject || focusSubject;
  return `${pageHeading('ONE THING AT A TIME', '此刻，只做一件事。', '给自己一段不被打扰的时间，和眼前的知识好好相处。')}<section class="focus-space"><div class="focus-leaf">${icon('leaf')}</div><div class="eyebrow">TIME TO GROW</div><h2 id="focus-title">${timer ? timer.running ? '正在专注，保持自己的节奏' : '休息一下，准备好再继续' : '准备好，开始一段专注'}</h2><div class="focus-subject"><label for="focus-subject">当前学科</label><select id="focus-subject" ${timer ? 'disabled' : ''}>${subjects.map(s => `<option value="${s.id}" ${selected === s.id ? 'selected' : ''}>${s.name}</option>`).join('')}</select></div><div class="focus-clock"><svg viewBox="0 0 280 280" aria-hidden="true"><circle cx="140" cy="140" r="128" class="timer-track"/><circle cx="140" cy="140" r="128" class="timer-progress" id="timer-ring"/></svg><div><span id="timer-digits">${String(focusDuration).padStart(2, '0')}:00</span><span id="timer-caption">让注意力，慢慢沉下来</span></div></div><div class="duration-selector">${[25, 50, 90].map(n => btn('duration', `${n} 分钟`, `${!timer && focusDuration === n ? 'active' : ''}`, `data-id="${n}" ${timer ? 'disabled' : ''}`)).join('')}</div><div class="focus-controls">${timer ? `${btn('timer-toggle', `${icon(timer.running ? 'pause' : 'play')} ${timer.running ? '暂停专注' : '继续专注'}`, 'btn btn-primary btn-large')}${btn('timer-finish', `${icon('check')} 结束并记录`, 'btn btn-white btn-large')}` : btn('timer-start', `${icon('play')} 开始专注`, 'btn btn-primary btn-large')}${timer ? btn('timer-cancel', '放弃本次', 'text-btn') : ''}</div><p class="focus-note">时间会自动记录。切换页面不会中断计时，暂停时间不计入专注。</p><div class="focus-today">今日已专注 <strong>${minutesText(actualMinutes(today()))}</strong><span>·</span>完成 <strong>${state.sessions.filter(s => s.date === today()).length} 次</strong></div></section>`;
}
function settingsView() {
  const a=state.settings, remaining=dayDiff(today(),a.examDate), phase=remaining>180?'当前以主科为主，可轻度熟悉政治。':remaining>90?'进入考前约 5–6 个月，可考虑系统复习政治。':'进入考前约 3 个月，可加强政治整理和回顾。';
  return `${pageHeading('MAKE IT YOURS','我的学习设置','选好科目和学习时间，保存即可生效；重新排计划请到学习计划页。')}
  <div class="settings-columns"><section class="panel"><form id="settings-form" class="settings-form">
  <label>怎么称呼你<input name="name" value="${esc(a.name)}" maxlength="40" required></label>
  <div class="form-grid"><label>数学科目<select name="mathExam"><option value="math2" ${a.mathExam==='math2'?'selected':''}>数学二</option><option value="math1" ${a.mathExam==='math1'?'selected':''}>数学一</option></select></label><label>英语科目<select name="englishExam"><option value="english2" ${a.englishExam==='english2'?'selected':''}>英语二</option><option value="english1" ${a.englishExam==='english1'?'selected':''}>英语一</option></select></label></div>
  <div class="form-grid"><label>计划起点<input type="date" name="startDate" value="${a.startDate}" required></label><label>目标初试日期<input type="date" name="examDate" value="${a.examDate}" required></label></div><p class="field-note">2028 年入学对应 2027 年底初试；默认日期仅用于规划，请按官方公告调整。</p>
  <div class="form-grid"><label>每天可用时间（小时）<input name="dailyHours" type="number" min="0.5" max="16" step="0.5" value="${a.dailyHours}" required></label><label>目标总分<input name="target" type="number" min="1" max="500" step="1" value="${a.target}" required></label></div>
  <fieldset class="study-days"><legend>每周可学习日</legend>${[1,2,3,4,5,6,0].map(d=>`<label><input type="checkbox" name="studyDays" value="${d}" ${a.studyDays.includes(d)?'checked':''}><span>周${'日一二三四五六'[d]}</span></label>`).join('')}</fieldset>
  <label>思想政治安排<select name="politicsMode"><option value="off" ${a.politicsMode==='off'?'selected':''}>不学习</option><option value="light" ${a.politicsMode==='light'?'selected':''}>轻度学习</option><option value="full" ${a.politicsMode==='full'?'selected':''}>全量学习</option></select></label>
  <div class="politics-guidance"><strong>${phase}</strong><p>早期可轻度熟悉；考前约 5–6 个月考虑系统复习，最后约 3 个月加强回顾。基础较弱可提前，这是可调整的阶段建议。到阶段时只提醒，不自动切换。</p><p>轻度每周 3 次 × 20 分钟，优先使用机动；全量在每天 4 小时时约 45 分钟，计入总预算并减少主科预排。时间不足则待安排。</p><a href="https://yz.chsi.com.cn/kyzx/jyxd/201705/20170510/1602631783.html" target="_blank" rel="noopener">查看规划参考</a></div>
  <button type="submit" class="btn btn-primary">保存设置</button>
  </form></section><aside>
  <section class="panel backup-panel"><h2>记录与备份</h2><p>覆盖1.0.5 使用独立学习记录，旧版原始数据保留，无需先手动备份。</p>${btn('export','导出完整备份','btn btn-primary full-width')}${btn('import','从备份恢复','btn btn-white full-width')}<input type="file" id="import-file" accept=".json,application/json" hidden>${btn('export-legacy','导出旧版原始记录','btn btn-white full-width')}</section>
  <section class="panel about-panel"><h2>轻舟 ${APP_VERSION}</h2><p>设置直接保存，计划由你确认。</p>${btn('show-changelog','查看更新说明','btn btn-white full-width')}</section>
  <section class="panel contact-panel"><h2>联系我们</h2><strong>轻舟项目开发者</strong><p>问题反馈与改进建议</p><span class="developer-email">2024304827@aust.edu.cn</span><div class="button-row">${btn('copy-email','复制邮箱','btn btn-white')}${btn('contact-developer','写邮件','btn btn-primary')}</div></section>
  <section class="panel about-panel"><h2>知识地图参考</h2><p>学习与练习在教材、课程和真题中完成，这里记录进度与安排。</p><div class="source-links">${sources.map(([label,url])=>`<a href="${url}" target="_blank" rel="noopener">${esc(label)}</a>`).join('')}</div></section></aside></div>`;
}

function updateTimerDisplay() {
  const seconds = remainingSeconds(), digits = `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`;
  const display = $('#timer-digits'); if (display) display.textContent = digits;
  const ring = $('#timer-ring'); if (ring) { ring.style.strokeDasharray = '804.25'; ring.style.strokeDashoffset = String(804.25 * (1 - seconds / (timer?.duration || focusDuration * 60))); }
  const live = $('.timer-live'); if (live) live.textContent = timer ? digits : '';
}

function capture(root){return [...(root?.querySelectorAll('input,select,textarea')||[])].map(e=>({key:e.id||e.name,value:e.value,checked:e.checked,type:e.type,disabled:e.disabled,readOnly:e.readOnly}));}
function restore(root,values){for(const v of values||[]){const nodes=[...(root?.querySelectorAll('input,select,textarea')||[])];const e=nodes.find(e=>(e.id||e.name)===v.key&&(e.type!=='checkbox'&&e.type!=='radio'||e.value===v.value));if(e){e.value=v.value;e.disabled=Boolean(v.disabled);if('readOnly'in e)e.readOnly=Boolean(v.readOnly);if(['checkbox','radio'].includes(e.type))e.checked=v.checked;}}}
function dirty(root){return !!root?.querySelector('[data-dirty="true"]');}
function resetDirty(){for(const e of document.querySelectorAll('[data-dirty]'))delete e.dataset.dirty;pageValues={};}
function blocked(){return !!storageError||needsOnboarding(state);}
function render(){
 const previous=$('#main'),values=capture(previous),active=document.activeElement?.id;
 window.qingzhouDesktop?.setStudyReady?.(!blocked()).catch(()=>{});
 if(storageError){$('#app').innerHTML=guideShell(`<section class="panel"><h1>恢复学习记录</h1><p class="save-error">${esc(storageError)}</p><p>不会用空白记录覆盖损坏记录。仅可恢复新版 v4 备份。</p><div class="button-row">${btn('export-raw','导出原始记录')}${btn('import','导入新版备份','btn btn-primary')}</div></section>`);return;}
 if(needsOnboarding(state)){$('#app').innerHTML=guideShell(onboardingStep==='plan'?draftView(true):onboardingChoices());return;}
 document.title=`${navItems.find(n=>n[0]===page)?.[2]} · 轻舟`;
 $('#app').innerHTML=`<aside class="sidebar"><a class="brand" href="#dashboard"><img src="/icon.svg" alt=""><div>轻舟<span>学习工作台 · 1.0.5</span></div></a><div class="workspace-tag">${examLabel()}</div><nav>${navItems.map(([id,i,name])=>`<a href="#${id}" class="nav-item ${page===id?'active':''}">${icon(i)}<span>${name}</span></a>`).join('')}</nav><div class="sidebar-bottom"><div class="user-card"><div class="avatar">${esc(state.settings.name.slice(0,1))}</div><div><strong>${esc(state.settings.name)}</strong><span>本机记录 · 每一步都算数</span></div></div></div></aside><div class="app-shell"><header class="topbar"><strong>${navItems.find(n=>n[0]===page)?.[2]}</strong><div class="top-actions"><span class="timer-live"></span>${btn('search',`${icon('search')} 搜索知识点 <kbd>Ctrl K</kbd>`,'search-button')}<span class="top-date">${niceDate(today(),{month:'long',day:'numeric',weekday:'long'})}</span></div></header><main id="main">${({dashboard:dashboardView,knowledge:knowledgeView,plan:planView,review:reviewView,analytics:analyticsView,focus:focusView,settings:settingsView})[page]()}${fieldError?`<p class="save-error" role="alert">${esc(fieldError)}</p>`:''}</main><footer class="app-footer">轻舟 · 让努力有迹可循</footer></div>`;
 if(dirty(previous)){restore($('#main'),values);$('#main form')?.setAttribute('data-dirty','true');if(active)document.getElementById(active)?.focus();}
 updateTimerDisplay();
}
function guideShell(content){return `<main id="main" class="onboarding-shell"><header class="onboarding-brand"><img src="/icon.svg" alt=""><div>轻舟<span>QINGZHOU · 1.0.5</span></div></header>${content}<p class="field-note">每一步，都算数。</p></main>`;}
function onboardingChoices(){const s=onboardingSettings;const choices=(name,list)=>list.map(([value,label])=>`<label class="onboarding-choice"><input type="radio" name="${name}" value="${value}" ${s[name]===value?'checked':''}><span><strong>${label}</strong></span></label>`).join('');return `<section class="onboarding-intro"><div class="eyebrow">开始新的学习记录</div><h1>选好科目，从这周开始。</h1><p>1.0.5 使用全新记录；旧版原始数据保留，可在设置中导出。</p></section><section class="panel onboarding-panel"><form id="onboarding-form"><fieldset><legend>数学科目</legend><div class="onboarding-options">${choices('mathExam',[['math2','数学二'],['math1','数学一']])}</div></fieldset><fieldset><legend>英语科目</legend><div class="onboarding-options">${choices('englishExam',[['english2','英语二'],['english1','英语一']])}</div></fieldset><fieldset><legend>政治安排</legend><div class="onboarding-options">${choices('politicsMode',[['off','不学习'],['light','轻度学习'],['full','全量学习']])}</div></fieldset><div class="onboarding-defaults">每日 4 小时 · 每周七天 · 目标初试 ${s.examDate}</div><p class="field-note">之后可在设置修改。仅安排本周今天及之后；确认计划后开始使用。</p><button class="btn btn-primary" type="submit">生成本周计划 ${icon('arrow')}</button></form></section>`;}
function navigate(next){if(blocked()){history.replaceState(null,'','#onboarding');render();return;}if(!navItems.some(n=>n[0]===next))next='dashboard';if(next!==page&&(dirty($('#main'))||dirty($('#modal-root')))){history.replaceState(null,'','#'+page);return protect(()=>navigateConfirmed(next));}navigateConfirmed(next);}
function navigateConfirmed(next){forceClose();resetDirty();page=next;history.replaceState(null,'','#'+next);render();window.scrollTo({top:0});}
function taskRow(t,readonly=false){return `<div class="task-row ${t.done?'completed':''}">${readonly?'<span class="topic-dot"></span>':btn('toggle-task',t.done?icon('check'):'','task-check',`data-id="${esc(t.id)}" aria-label="${t.done?'撤销完成':'完成'} ${esc(t.title)}"`)}<div class="task-body"><strong>${esc(t.title)}</strong><p>${esc(taskSubjectName(t))} · ${minutesText(t.minutes)} · ${t.kind==='review'?'复习':t.kind==='practice'?'查漏巩固':'基础学习'}${t.queued?` · 待安排：${esc(t.queueReason)}`:''}${t.restrictionReason?` · ${esc(t.restrictionReason)}`:''}${t.planWeek&&t.planWeek!==monday(t.date)?` · 来自 ${t.planWeek} 周`:''}</p></div>${!readonly&&!t.done?`<div class="task-actions">${btn('task-focus',icon('play'),'icon-btn',`data-id="${esc(t.id)}" aria-label="开始 ${esc(t.title)}"`)}${btn('edit-task','编辑','text-btn',`data-id="${esc(t.id)}"`)}${btn(t.origin==='manual'?'delete-task':'adjust-task',t.origin==='manual'?'删除':'顺延 / 暂停','text-btn',`data-id="${esc(t.id)}"`)}</div>`:''}</div>`;}
function calendar(data,start,readonly=false){const b=timeBudget(data.settings);return `<div class="draft-grid">${Array.from({length:7},(_,i)=>{const date=addDays(start,i),list=data.tasks.filter(t=>t.date===date&&!t.queued&&!t.suspended),used=list.reduce((n,t)=>n+t.minutes,0),study=isStudy(data.settings,date);return `<section class="panel draft-day ${study?'':'rest-day'} ${date===today()?'today-day':''}"><div class="panel-heading"><h2>${niceDate(date,{month:'numeric',day:'numeric',weekday:'short'})}</h2><span class="status-tag">${study?'学习日':'休息日'}</span></div><p class="small-muted">${minutesText(used)} / ${minutesText(b.full)} · 机动 ${minutesText(Math.min(b.reserve,Math.max(0,b.full-used)))}</p>${list.length?list.map(t=>taskRow(t,readonly)).join(''):'<p class="panel-empty-text">没有安排</p>'}${data.adjustments?.filter(a=>a.active&&a.type==='course'&&a.from===date).map(a=>`<p class="course-pause">${esc(subjectById[a.subject].name)}课程暂停一天</p>`).join('')||''}</section>`;}).join('')}</div>`;}
const isStudy=(settings,date)=>settings.studyDays.includes(new Date(date+'T12:00:00').getDay());
function planView(){if(draft)return draftView();const b=timeBudget(state.settings),w=state.weeks[weekStart],backlog=state.tasks.filter(t=>t.queued&&!t.done),future=state.tasks.filter(t=>!t.done&&!t.suspended&&!t.queued&&t.date>addDays(weekStart,6));return `${pageHeading('本周原版 + 可撤销调整','学习计划','周一到周日。顺延保留内容和时长；完成记录不随恢复撤销。',`<div class="button-row">${btn('add-task','加入想学的内容','btn btn-white')}${btn('generate',w?'重新生成':'生成本周计划','btn btn-primary')}</div>`)}${state.planNeedsReview?'<div class="plan-alert">学习安排已更新，可重新生成计划。</div>':''}<section class="panel calendar-panel"><div class="panel-heading"><h2>${weekStart} — ${addDays(weekStart,6)}</h2><div class="button-row">${btn('week-prev','上一周','btn btn-small')}${btn('today','本周','btn btn-small')}${btn('week-next','下一周','btn btn-small')}${w?btn('original','查看原版','btn btn-white'):''}${w&&weekStart===monday(today())?btn('restore-default','恢复默认计划','btn btn-white'):''}</div></div><p class="field-note">每日预算 ${minutesText(b.full)}，通常预留 ${minutesText(b.reserve)} 机动。学习日与设置同步。</p></section>${calendar(state,weekStart,weekStart<monday(today()))}${backlog.length?`<section class="panel"><h2>待安排 · ${backlog.length}</h2>${backlog.map(t=>taskRow(t)).join('')}</section>`:''}${future.length?`<section class="panel"><h2>已顺延到后续日期 · ${future.length}</h2>${future.map(t=>`<p class="small-muted">${t.date}</p>${taskRow(t)}`).join('')}</section>`:''}${adjustmentsView()}`;}
function adjustmentsView(){const restrictions=state.restrictions||[];const list=state.adjustments.filter(a=>a.active&&['single','course','pause','missed','add','edit','delete'].includes(a.type));return `<section class="panel"><div class="panel-heading"><h2>计划调整 · ${list.length+restrictions.length}</h2>${undoIds.length?btn('undo-adjustment','撤销上次调整','btn btn-white'):''}</div>${list.map(a=>{const t=state.tasks.find(t=>t.id===a.taskId)||a.task||Object.values(state.weeks).flatMap(w=>w.original).find(t=>t.id===a.taskId)||topicById[a.topicId];return `<div class="exclusion-row"><span><strong>${{single:'单个知识点顺延',course:'整门课程顺延',pause:'永久暂停',missed:'漏学自动顺延',add:'新增任务',edit:'任务编辑',delete:'自加任务删除'}[a.type]}</strong> · ${esc(t?.title||subjectById[a.subject]?.name||'任务')}<small>来源周 ${a.week} · ${a.from||a.created}${a.to?` → ${a.to}`:''}${a.moves?` · ${a.moves.length} 项接力后移`:''}</small></span>${a.type==='missed'?'<span class="small-muted">系统记录，防止重复顺延</span>':btn('cancel-adjustment','恢复 / 撤销','btn btn-white',`data-id="${a.id}"`)}</div>`;}).join('')||'<p class="panel-empty-text">暂无调整。</p>'}${restrictions.map(r=>`<div class="exclusion-row"><span><strong>系统限制顺延</strong> · ${esc(state.tasks.find(t=>t.id===r.taskId)?.title)}<small>来源周 ${r.week} · ${r.from} → ${r.to||'待安排'} · ${esc(r.reason)}</small></span>${btn('settings','修改学习日 / 预算','btn btn-white')}</div>`).join('')}<p class="field-note">取消暂停按原版和目录顺序接回，取消先后不影响结果。完成记录始终保留。</p></section>`;}
function draftView(guide=false){const data=guide?{...guideState,tasks:guideState.draft.tasks,adjustments:guideState.draft.adjustments}:draft.candidate,start=guide?guideState.draft.week:draft.start,queued=data.tasks.filter(t=>t.queued&&!t.done);return `${pageHeading('草案编辑模式',guide?'确认本周计划，开始使用':'核对你的本周草案','编辑自动保留；确认前不会改变正式安排。首次引导关闭后从头选择。')}<div class="draft-toolbar"><div><strong>${start} — ${addDays(start,6)}</strong><span>${(guide?guideState.draft:state.draft).summary.join(' ')} · 待安排 ${queued.length} 项</span></div><div class="button-row">${btn('add-task','加入内容','btn btn-white')}${guide?`${btn('onboarding-back','返回选择','btn btn-white')}${btn('confirm-onboarding','确认计划并开始使用','btn btn-primary')}`:`${draftStale(state)?btn('recheck-draft','重新核对','btn btn-primary'):btn('confirm-draft','确认计划','btn btn-primary')}${btn('cancel-draft','取消草案','btn btn-white')}`}</div></div>${!guide&&draftStale(state)?'<p class="plan-alert">日期或记录已有变化。重新核对会保留你的编辑意图。</p>':''}${calendar(data,start)}${data.tasks.filter(t=>!t.done&&!t.queued&&!t.suspended&&t.date>addDays(start,6)).length?`<section class="panel"><h2>后续顺延安排</h2>${data.tasks.filter(t=>!t.done&&!t.queued&&!t.suspended&&t.date>addDays(start,6)).map(t=>`<p>${t.date}</p>${taskRow(t)}`).join('')}</section>`:''}${queued.length?`<section class="panel"><h2>待安排 · ${queued.length}</h2>${queued.map(t=>taskRow(t)).join('')}</section>`:''}<section class="panel"><h2>修改摘要</h2><p>已编辑 ${data.adjustments.filter(a=>a.active&&a.type!=='missed').length} 项。新安排不会改写本周原版。</p></section>`;}
function applyOperation(intent){if(needsOnboarding(state)){try{guideState=evaluatePlan(guideState,{command:{type:'draft-command',intent}}).state;render();return true;}catch(e){toast(e.message);return false;}}return transact(state.draft?{type:'draft-command',week:state.draft.week,intent}:intent);}
function actualTask(id){const data=needsOnboarding(state)?guideState:state;return (data.draft?.tasks||data.tasks).find(t=>t.id===id);}
function openModal(content,wide=false,meta=null){if(!modalContent||!$('#modal-root').children.length)returnFocus=document.activeElement;modalContent=content;modalOptions={wide};if(meta)modal=meta;$('#modal-root').innerHTML=`<div class="modal-backdrop" data-action="backdrop"><section class="modal ${wide?'modal-wide':''}" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><header class="dialog-header"><span>轻舟学习助手</span>${btn('close-modal',icon('close'),'icon-btn','aria-label="关闭"')}</header><div class="dialog-scroll">${content}</div></section></div>`;const dialog=$('.modal'),title=$('#dialog-title'),footer=dialog.querySelector('.modal-bottom');if(title){dialog.querySelector('.dialog-header span').replaceWith(title);}if(footer){for(const button of footer.querySelectorAll('[type="submit"]')){const form=button.closest('form');if(form)button.setAttribute('form',form.getAttribute('id'));}dialog.append(footer);}$('#app').inert=true;document.body.classList.add('modal-open');queueMicrotask(()=>$('.modal input:not([type="hidden"]),.modal textarea,.modal select,.modal button')?.focus());}
function forceClose(){modalStack=[];$('#modal-root').innerHTML='';document.body.classList.remove('modal-open');$('#app').inert=false;modalContent='';modal=null;if(returnFocus?.isConnected)returnFocus.focus();else {const h=$('#main h1');if(h){h.tabIndex=-1;h.focus();}}}
function pushModal(content,meta,wide=false){if(!$('#modal-root').children.length)return openModal(content,wide,meta);modalStack.push({content:modalContent,options:modalOptions,meta:modal,values:capture($('#modal-root')),dirty:dirty($('#modal-root')),focus:document.activeElement});openModal(content,wide,meta);}
function popModal(){const back=modalStack.pop();if(!back)return forceClose();openModal(back.content,back.options.wide,back.meta);restore($('#modal-root'),back.values);if(modal?.type==='task-editor'){const topic=topicById[modal.topicId];$('#choose-topic').textContent=topic?.title||'选择知识点';$('#task-subject').disabled=Boolean(topic);if(topic)$('#task-subject').value=topic.subject;}if(fieldError&&$('#modal-root form')&&!$('#modal-root .save-error')){const error=document.createElement('p');error.className='save-error';error.setAttribute('role','alert');error.textContent=fieldError;$('#modal-root form').prepend(error);}if(back.dirty)$('#modal-root form')?.setAttribute('data-dirty','true');queueMicrotask(()=>{const key=back.focus?.id||back.focus?.name;if(key)[...$('#modal-root').querySelectorAll('input,select,textarea,button')].find(e=>(e.id||e.name)===key)?.focus();});}
let pendingAction=null;
function protect(action){pendingAction=action;pushModal(`<h2 id="dialog-title">还有未保存的输入</h2><p>返回继续编辑，或放弃这次输入。已保存的学习记录与草案不受影响。</p><div class="modal-bottom">${btn('keep-editing','继续编辑','btn btn-primary')}${btn('discard-input','放弃输入并继续','btn btn-white')}</div>`,{type:'input-protection'});}
function closeModal(){if(modalStack.length){if(dirty($('#modal-root')))return protect(()=>popModal());return popModal();}if(dirty($('#modal-root')))return protect(()=>forceClose());forceClose();}
function showAddTask(id=null,topicId=null){const data=dataNow(),task=id?actualTask(id):null;if(task?.done)return;modal={type:'task-editor',id,topicId:task?.topicId||topicId};const topic=topicById[modal.topicId];const subjects=activeSubjects(data.settings);openModal(`<h2 id="dialog-title">${task?'编辑任务':'加入想学的内容'}</h2><p class="modal-subtitle">绑定知识点后学科固定；更换知识点保留你写的标题。</p><form id="task-form" class="settings-form"><label>知识点（可不绑定）<div class="button-row">${btn('pick-topic',topic?esc(topic.title):'选择知识点','btn btn-white','id="choose-topic"')}${btn('clear-topic','解除绑定','text-btn')}</div></label><label>任务内容<input id="task-title" name="title" value="${esc(task?.title||topic?.title||'')}" maxlength="200" required></label><div class="form-grid"><label>所属课程<select id="task-subject" name="subject" ${topic?'disabled':''}>${subjects.map(s=>`<option value="${s.id}" ${s.id===(topic?.subject||task?.subject||'math')?'selected':''}>${esc(displaySubjectName(s,data.settings))}</option>`).join('')}</select></label><label>类型<select name="kind">${[['learn','基础学习'],['practice','查漏巩固'],['review','复习回顾']].map(([v,l])=>`<option value="${v}" ${task?.kind===v?'selected':''}>${l}</option>`).join('')}</select></label></div><div class="form-grid"><label>日期<input name="date" type="date" value="${task?.date||today()}" required></label><label>时长（分钟）<input name="minutes" type="number" min="1" max="960" step="any" value="${task?.minutes||topic?.minutes||45}" required></label></div><div class="modal-bottom">${btn('close-modal','返回','btn btn-white')}<button class="btn btn-primary" type="submit">保存${data.draft?'到草案':''}</button></div></form>`,false,modal);}
let pickerQuery='',pickerCourse='all',pickerSelected=null,pickerIndex=0;
function pickerResults(){return activeTopics(dataNow().settings).filter(t=>(pickerCourse==='all'||t.subject===pickerCourse)&&(`${t.title} ${subjectById[t.subject].name} ${subjectById[t.subject].chapters.find(c=>c.id===t.chapter)?.title}`).toLowerCase().includes(pickerQuery.toLowerCase()));}
function paintPicker(){const list=pickerResults();pickerIndex=Math.min(pickerIndex,Math.max(0,list.length-1));$('#picker-count').textContent=`${list.length} 个结果 · 可滚动查看全部`;$('#picker-results').innerHTML=list.map((t,i)=>`<button type="button" tabindex="-1" role="option" aria-selected="${t.id===pickerSelected}" id="option-${i}" class="picker-option ${t.id===pickerSelected?'selected':''}" data-action="select-topic" data-id="${t.id}"><strong>${esc(t.title)}</strong><small>${esc(displaySubjectName(subjectById[t.subject],dataNow().settings))} · ${esc(subjectById[t.subject].chapters.find(c=>c.id===t.chapter)?.title)}</small></button>`).join('')||'<p class="panel-empty-text">没有匹配结果。</p>';$('#picker-results').setAttribute('aria-activedescendant',`option-${pickerIndex}`);$('#picker-search').setAttribute('aria-activedescendant',`option-${pickerIndex}`);}
function showPicker(search=false){pickerQuery='';pickerCourse='all';pickerSelected=modal?.topicId||null;pickerIndex=0;const content=`<h2 id="dialog-title">${search?'搜索学习内容':'选择知识点'}</h2><div class="picker-filters"><input id="picker-search" role="combobox" aria-expanded="true" aria-controls="picker-results" aria-autocomplete="list" aria-label="搜索知识点、课程或章节" placeholder="搜索知识点、课程或章节"><select id="picker-course" aria-label="筛选课程"><option value="all">全部课程</option>${activeSubjects(dataNow().settings).map(s=>`<option value="${s.id}">${esc(displaySubjectName(s,dataNow().settings))}</option>`).join('')}</select></div><p id="picker-count" class="small-muted"></p><div id="picker-results" role="listbox" tabindex="0" aria-label="知识点结果"></div><div class="modal-bottom">${btn('close-modal','返回','btn btn-white')}${btn(search?'open-picked-topic':'confirm-picked-topic',search?'查看知识点':'确认选择','btn btn-primary')}</div>`;if(modal)pushModal(content,{type:search?'search':'picker'},true);else openModal(content,true,{type:search?'search':'picker'});paintPicker();$('#picker-search').focus();}
function showTopic(id){const t=topicById[id],s=subjectById[t.subject],p=state.progress[id],weak=state.weakPoints[id],c=s.chapters.find(c=>c.id===t.chapter);const content=`<h2 id="dialog-title">${esc(t.title)}</h2><p class="modal-subtitle">${esc(s.name)} · ${esc(c.title)}</p><div class="topic-detail-section"><h3>学习目标</h3><p>${esc(c.goal)}</p><p>${esc(s.method)}</p></div><h3>掌握自评</h3><div class="level-options">${levels.map((l,i)=>btn('set-level',l,`level-option ${i===(p?.level||0)?'selected':''}`,`data-id="${id}" data-level="${i}"`)).join('')}</div><form id="note-form" class="settings-form"><input type="hidden" name="id" value="${id}"><label class="checkbox-field"><input name="weak" type="checkbox" ${weak?'checked':''}>需要加强</label><label>不熟悉的原因<input name="weakReason" maxlength="1000" value="${esc(weak?.reason||'')}"></label><label>学习笔记<textarea name="note" rows="8" maxlength="20000">${esc(state.notes[id]||'')}</textarea></label><div class="modal-bottom">${btn('topic-to-plan','加入计划','btn btn-white',`data-id="${id}"`)}<button type="submit" class="btn btn-primary">保存记录</button></div></form>`;if(modal)pushModal(content,{type:'topic',id},true);else openModal(content,true,{type:'topic',id});}
function startFocus(subject){if(!timer){focusSubject=subject||focusSubject;timer={id:uid(),subject:focusSubject,duration:focusDuration*60,remaining:focusDuration*60,until:Date.now()+focusDuration*60000,running:true,...(currentTrackForSubject(focusSubject)?{examTrack:currentTrackForSubject(focusSubject)}:{})};persistTimer();}navigate('focus');}
function finishTimer(auto=false){if(!timer)return;const finished=timer,elapsed=finished.duration-remainingSeconds();const candidate=structuredClone(state);if(elapsed>0&&!candidate.sessions.some(s=>s.id===finished.id))candidate.sessions.push({id:finished.id,date:auto?dateKey(new Date(finished.until)):today(),subject:finished.subject,minutes:Math.round(elapsed/60*100)/100||.01,...(finished.examTrack?{examTrack:finished.examTrack}:{})});if(!save(candidate)){timer.remaining=remainingSeconds();timer.running=false;persistTimer();return;}timer=null;persistTimer();render();toast('专注已记录，给自己一点休息。');}
function showChangelog(){openModal(`<h2 id="dialog-title">轻舟 1.0.5 更新说明</h2><ul class="release-list"><li>固定周一到周日，本周原版永久保留。</li><li>单点、整门课程与漏学顺延统一处理，支持撤销和恢复默认。</li><li>普通草案关闭后保留；完成事实与任务安排独立。</li><li>全新绿色工作台，全部知识点可搜索、筛选和滚动选择。</li><li>统一弹窗返回与未保存输入保护。</li><li>采用独立 v4 记录；旧版原始数据保留，仅支持新版备份恢复。</li></ul><div class="modal-bottom">${btn('close-modal','知道了','btn btn-primary')}</div>`,true);}
async function exportData(raw=false,legacy=false){const records={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('qingzhou.')&&(!legacy||k!==KEY&&k!==TIMER_KEY))records[k]=localStorage.getItem(k);}const content=JSON.stringify(raw||legacy?{rawRecords:records}:validateState(state));if(new TextEncoder().encode(content).length>BACKUP_LIMIT)return toast('备份超过 30 MiB，请精简记录。');try{const result=await window.qingzhouDesktop.saveBackup(content,`轻舟${legacy?'旧版原始记录':raw?'原始记录':'新版备份'}-${today()}.json`);if(result.saved)toast('备份已保存。');else if(result.error)toast(result.error);}catch(e){toast('导出失败，输入和记录保留。');}}
function importFile(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{const file=input.files[0];if(!file)return;if(file.size>BACKUP_LIMIT)return toast('备份不得超过 30 MiB。');try{const candidate=validateState(JSON.parse(await file.text()));pushModal(`<h2 id="dialog-title">恢复新版备份？</h2><p>恢复 ${candidate.tasks.length} 项任务、${candidate.completions.length} 条完成记录及所有周计划。会替换当前新版记录，旧版原始数据不变。</p><div class="modal-bottom">${btn('close-modal','返回','btn btn-white')}${btn('confirm-import','确认恢复','btn btn-primary')}</div>`,{type:'import',candidate});}catch(e){toast(e.message);}};input.click();}

document.addEventListener('input',event=>{
 const form=event.target.closest('form');if(form)form.dataset.dirty='true';
 if(event.target.id==='picker-search'){pickerQuery=event.target.value;pickerSelected=null;pickerIndex=0;paintPicker();}
 if(event.target.id==='knowledge-search'){knowledgeQuery=event.target.value;const selection=event.target.selectionStart;render();const next=$('#knowledge-search');next?.focus();next?.setSelectionRange(selection,selection);}
});
document.addEventListener('change',event=>{if(event.target.id==='picker-course'){pickerCourse=event.target.value;pickerSelected=null;pickerIndex=0;paintPicker();}if(event.target.id==='focus-subject')focusSubject=event.target.value;});
document.addEventListener('click',async event=>{
 const link=event.target.closest('a[href^="#"]');if(link){event.preventDefault();return navigate(link.hash.slice(1));}
 const el=event.target.closest('[data-action]');if(!el)return;const action=el.dataset.action,id=el.dataset.id;
 if(action==='backdrop'&&event.target!==el)return;
 if(storageError&&!['import','confirm-import','export-raw','close-modal','backdrop','keep-editing','discard-input'].includes(action))return;
 if(needsOnboarding(state)&&!storageError&&!['onboarding-back','confirm-onboarding','add-task','edit-task','delete-task','adjust-task','single-delay','course-delay','permanent-pause','close-modal','backdrop','pick-topic','clear-topic','select-topic','confirm-picked-topic','keep-editing','discard-input','replace-guide'].includes(action))return;
 if(navItems.some(n=>n[0]===action))return navigate(action);
 switch(action){
 case 'close-modal':case 'backdrop':closeModal();break;
 case 'keep-editing':popModal();pendingAction=null;break;
 case 'discard-input':{const action=pendingAction;pendingAction=null;popModal();resetDirty();if(action)action();break;}
 case 'group':filter=id;knowledgeQuery='';navigate('knowledge');break;
 case 'filter':filter=id;render();break;
 case 'subject':selectedSubject=id;expanded.clear();render();break;
 case 'chapter':{if(!expanded.size)expanded.add(currentSubjects().find(s=>s.id===selectedSubject).chapters[0].id);if(expanded.has(id))expanded.delete(id);else expanded.add(id);expanded.add('__initialized');render();break;}
 case 'cycle-level':{const c=structuredClone(state);setLevel(c,id,((c.progress[id]?.level||0)+1)%4);if(save(c))render();break;}
 case 'set-level':{const c=structuredClone(state);setLevel(c,id,Number(el.dataset.level));if(save(c)){for(const b of $('.level-options').children)b.classList.toggle('selected',b.dataset.level===el.dataset.level);}break;}
 case 'topic':if(dirty($('#modal-root')))protect(()=>showTopic(id));else showTopic(id);break;
 case 'topic-to-plan':{const go=()=>{forceClose();showAddTask(null,id);};if(dirty($('#modal-root')))protect(go);else go();break;}
 case 'toggle-task':{if(state.draft||needsOnboarding(state))break;const c=structuredClone(state);completeTask(c,id);if(save(c))render();break;}
 case 'add-task':showAddTask();break;
 case 'edit-task':showAddTask(id);break;
 case 'delete-task':{if(applyOperation({type:'delete',taskId:id}))toast('自加任务已删除，可撤销；不会屏蔽知识点。');break;}
 case 'adjust-task':{const t=actualTask(id);if(!t)break;openModal(`<h2 id="dialog-title">调整：${esc(t.title)}</h2><p>保留时长与完成记录，跳过休息日。三种操作含义不同。</p><div class="adjust-options">${btn('single-delay','只顺延这个知识点到下一个学习日','btn btn-white',`data-id="${id}"`)}${btn('course-delay',`从 ${t.date} 起整门 ${esc(subjectById[t.subject].name)} 接力顺延`,'btn btn-white',`data-id="${id}"`)}${t.topicId?btn('permanent-pause','永久暂停这个知识点，直到恢复','btn btn-white',`data-id="${id}"`):''}</div><div class="modal-bottom">${btn('close-modal','返回','btn btn-primary')}</div>`,false,{type:'adjust',id});break;}
 case 'single-delay':case 'course-delay':case 'permanent-pause':{const t=actualTask(id),type={'single-delay':'single','course-delay':'course','permanent-pause':'pause'}[action];if(applyOperation({type,taskId:id,subject:t.subject,from:t.date,topicId:t.topicId})){forceClose();toast(state.draft||needsOnboarding(state)?'草案已调整':'调整已保存，可撤销。');}break;}
 case 'cancel-adjustment':transact({type:'cancel-adjustment',id});break;
 case 'undo-adjustment':{const last=undoIds.pop();if(last)transact({type:'cancel-adjustment',id:last});break;}
 case 'generate':{const go=()=>{transact({type:state.weeks[monday(today())]?'regenerate':'generate'});weekStart=monday(today());};if(state.draft){pushModal(`<h2 id="dialog-title">替换当前草案？</h2><p>当前草案的编辑会被替换；本周原版与正式任务保持。</p><div class="modal-bottom">${btn('close-modal','保留草案','btn btn-white')}${btn('replace-draft','重新生成','btn btn-primary')}</div>`,{type:'replace-draft',go});}else go();break;}
 case 'replace-draft':{const go=modal.go;forceClose();go();break;}
 case 'confirm-draft':if(transact({type:'confirm'}))toast('本周计划已确认。');break;
 case 'cancel-draft':transact({type:'cancel-draft'});break;
 case 'recheck-draft':transact({type:'recheck-draft',week:state.draft.week});break;
 case 'original':{const w=state.weeks[weekStart];if(w)openModal(`<h2 id="dialog-title">本周原版 · 只读</h2><p>首次生成于 ${w.created}。后续编辑不会改变这里。</p>${calendar({...state,tasks:w.original},weekStart,true)}${w.original.filter(t=>t.queued).length?`<h3>原版待安排</h3>${w.original.filter(t=>t.queued).map(t=>taskRow(t,true)).join('')}`:''}<div class="modal-bottom">${btn('close-modal','返回当前安排','btn btn-primary')}</div>`,true,{type:'original'});break;}
 case 'restore-default':openModal(`<h2 id="dialog-title">恢复本周默认计划？</h2><p>撤销本周 ${state.adjustments.filter(a=>a.active&&a.week===weekStart&&a.type!=='missed').length} 项人为新增、编辑、顺延与暂停。</p><p>保留 ${state.completions.length} 条实际完成记录；不回滚设置。恢复后仍按当前漏学、学习日与预算顺延。</p><div class="modal-bottom">${btn('close-modal','返回','btn btn-white')}${btn('confirm-restore','确认恢复默认','btn btn-primary')}</div>`,false,{type:'restore',week:weekStart});break;
 case 'confirm-restore':{const week=modal.week;if(transact({type:'restore',week}))forceClose();break;}
 case 'week-prev':weekStart=addDays(weekStart,-7);render();break;
 case 'week-next':weekStart=addDays(weekStart,7);render();break;
 case 'today':case 'today-plan':weekStart=monday(today());selectedDate=today();navigate('plan');break;
 case 'learning-heatmap':navigate('analytics');$('.heatmap')?.scrollIntoView({block:'center'});break;
 case 'search':if(dirty($('#modal-root')))protect(()=>showPicker(true));else showPicker(true);break;
 case 'pick-topic':showPicker();break;
 case 'clear-topic':modal.topicId=null;$('#task-subject').disabled=false;$('#choose-topic').textContent='选择知识点';$('#task-form').dataset.dirty='true';break;
 case 'select-topic':pickerSelected=id;pickerIndex=pickerResults().findIndex(t=>t.id===id);paintPicker();break;
 case 'confirm-picked-topic':{if(!pickerSelected)return toast('先选择一个知识点。');const t=topicById[pickerSelected];popModal();modal.topicId=t.id;$('#task-subject').value=t.subject;$('#task-subject').disabled=true;$('#choose-topic').textContent=t.title;if(!$('#task-title').value.trim())$('#task-title').value=t.title;$('#task-form').dataset.dirty='true';break;}
 case 'open-picked-topic':if(!pickerSelected)return toast('先选择一个知识点。');showTopic(pickerSelected);break;
 case 'review-again':case 'review-good':{const c=structuredClone(state);reviewTopic(c,id,action==='review-again'?'again':'good');if(save(c))render();break;}
 case 'chart-range':chartRange=+id;render();break;
 case 'duration':focusDuration=+id;render();break;
 case 'start-today':startFocus(plannedTasks(today()).find(t=>!t.done)?.subject);break;
 case 'task-focus':startFocus(actualTask(id)?.subject);break;
 case 'timer-start':startFocus($('#focus-subject')?.value||focusSubject);break;
 case 'timer-toggle':if(timer){timer.remaining=remainingSeconds();timer.running=!timer.running;timer.until=Date.now()+timer.remaining*1000;persistTimer();render();}break;
 case 'timer-finish':finishTimer();break;
 case 'timer-cancel':if(timer){openModal(`<h2 id="dialog-title">放弃本次专注？</h2><p>这段时间不会计入专注记录。</p><div class="modal-bottom">${btn('close-modal','继续专注','btn btn-primary')}${btn('confirm-cancel-timer','放弃本次','btn btn-white')}</div>`);}break;
 case 'confirm-cancel-timer':timer=null;persistTimer();forceClose();render();break;
 case 'onboarding-back':onboardingSettings={...guideState.settings};onboardingStep='subjects';forceClose();render();break;
 case 'replace-guide':{const next=modal.next;forceClose();makeGuide(next);break;}
 case 'confirm-onboarding':{try{let c=evaluatePlan(guideState,{command:{type:'confirm'}}).state;c.onboardingCompleted=true;if(save(c)){forceClose();navigate('dashboard');}}catch(e){toast(e.message);}break;}
 case 'keep-time-settings':applySettings(modal.next);break;
 case 'save-settings-discard':{const next=modal.next;if(next.dailyHours>=10&&next.dailyHours!==state.settings.dailyHours){openModal(`<h2 id="dialog-title">也给休息留点时间</h2><p>每天 ${next.dailyHours} 小时安排较长，请给睡眠、吃饭和休息留时间。10 小时是软件提醒阈值。</p><div class="modal-bottom">${btn('close-modal','调整时间','btn btn-white')}${btn('keep-time-settings','保持设置','btn btn-primary')}</div>`,false,{next});}else applySettings(next);break;}
 case 'return-to-draft':forceClose();resetDirty();navigate('plan');break;
 case 'export':await exportData();break;
 case 'export-raw':await exportData(true);break;
 case 'export-legacy':await exportData(false,true);break;
 case 'import':if(dirty($('#main'))||dirty($('#modal-root')))protect(()=>importFile());else importFile();break;
 case 'confirm-import':{const c=modal.candidate;if(save(c)){storageError='';timer=null;persistTimer();forceClose();resetDirty();navigate('dashboard');toast('新版备份已恢复。');}break;}
 case 'copy-email':{try{const r=await window.qingzhouDesktop.copyDeveloperEmail();toast(r.ok?'邮箱已复制。':'复制失败，可直接选取邮箱。');}catch{toast('可直接选取邮箱。');}break;}
 case 'contact-developer':{try{const r=await window.qingzhouDesktop.contactDeveloper();if(!r.ok)toast('请复制邮箱，在邮件客户端联系。');}catch{toast('请复制邮箱，在邮件客户端联系。');}break;}
 case 'show-changelog':showChangelog();break;
 case 'method':openModal(`<h2 id="dialog-title">记录你的掌握程度</h2><p>未开始 0% · 学习中 25% · 已学过 65% · 已掌握 100%。</p><p>完成任务只推进学习顺序，不改变掌握自评。复习与薄弱回访单独计算时间。</p><div class="modal-bottom">${btn('close-modal','明白了','btn btn-primary')}</div>`);break;
 }
});
function makeGuide(settings){guideState=createState();guideState.settings={...settings};guideState=evaluatePlan(guideState,{command:{type:'generate'}}).state;onboardingSettings={...settings};onboardingStep='plan';render();}
function applySettings(next){const c=reconcileSettings(state,next);c.draft=null;if(save(c)){resetDirty();forceClose();render();toast('设置已保存，学习日与计划同步调整。');}}
document.addEventListener('submit',event=>{
 event.preventDefault();const form=event.target,d=new FormData(form);
 if(form.getAttribute('id')==='onboarding-form'){const next={...onboardingSettings,mathExam:d.get('mathExam'),englishExam:d.get('englishExam'),politicsMode:d.get('politicsMode'),politics:d.get('politicsMode')!=='off'};if(guideState.draft){openModal(`<h2 id="dialog-title">替换未确认的引导草案？</h2><p>重新生成将替换当前草案。未确认前不会写入学习记录。</p><div class="modal-bottom">${btn('close-modal','返回','btn btn-white')}${btn('replace-guide','重新生成','btn btn-primary')}</div>`,false,{next});}else makeGuide(next);return;}
 if(form.getAttribute('id')==='task-form'){const id=modal.id,t=id?actualTask(id):null;const patch={title:d.get('title').trim(),subject:modal.topicId?topicById[modal.topicId].subject:d.get('subject'),topicId:modal.topicId||null,kind:d.get('kind'),date:d.get('date'),minutes:+d.get('minutes')};if(!patch.title)return;const task={id:uid(),...patch,origin:'manual',planWeek:monday(today()),sequence:dataNow().nextSequence++,done:false,queued:false};if(applyOperation(t?{type:'edit',taskId:id,patch}:{type:'add',task})){forceClose();render();toast('任务已保存。');}return;}
 if(form.getAttribute('id')==='note-form'){const c=structuredClone(state),id=d.get('id');c.notes[id]=d.get('note');if(d.has('weak'))c.weakPoints[id]={reason:d.get('weakReason').trim(),markedAt:c.weakPoints[id]?.markedAt||today()};else delete c.weakPoints[id];if(save(c)){form.removeAttribute('data-dirty');toast('记录已保存。');render();}return;}
 if(form.getAttribute('id')==='settings-form'){const next={...state.settings,name:d.get('name').trim()||'同学',startDate:d.get('startDate'),examDate:d.get('examDate'),dailyHours:+d.get('dailyHours'),target:+d.get('target'),mathExam:d.get('mathExam'),englishExam:d.get('englishExam'),politicsMode:d.get('politicsMode'),politics:d.get('politicsMode')!=='off',studyDays:d.getAll('studyDays').map(Number).sort()};try{validateState({...state,settings:next});}catch(e){toast(e.message);return;}if(state.draft&&JSON.stringify(next)!==JSON.stringify(state.settings)){openModal(`<h2 id="dialog-title">存在未确认草案</h2><p>保存新设置会丢弃当前草案。取消或保存失败保留设置输入和草案。</p><div class="modal-bottom">${btn('return-to-draft','返回草案','btn btn-white')}${btn('save-settings-discard','保存设置并丢弃草案','btn btn-primary')}</div>`,false,{next});return;}if(next.dailyHours>=10&&next.dailyHours!==state.settings.dailyHours){openModal(`<h2 id="dialog-title">也给休息留点时间</h2><p>每天 ${next.dailyHours} 小时的安排较长，睡眠、吃饭与休息同样重要。10 小时是软件提醒阈值。</p><div class="modal-bottom">${btn('close-modal','调整时间','btn btn-white')}${btn('keep-time-settings','保持设置','btn btn-primary')}</div>`,false,{next});return;}applySettings(next);}
});
document.addEventListener('keydown',event=>{
 if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();if(!blocked()){if(dirty($('#modal-root')))protect(()=>showPicker(true));else showPicker(true);}return;}
 if(event.key==='Escape'){event.preventDefault();if(modal)closeModal();return;}
 if(['picker','search'].includes(modal?.type)&&['ArrowDown','ArrowUp','Enter'].includes(event.key)&&event.target.id!=='picker-course'&&(event.target.tagName!=='BUTTON'||event.target.classList.contains('picker-option'))){const list=pickerResults();if(event.key==='Enter'){if(!list.length)return;pickerSelected=pickerSelected||list[pickerIndex].id;document.querySelector(`[data-action="${modal.type==='search'?'open-picked-topic':'confirm-picked-topic'}"]`).click();}else{pickerIndex=Math.max(0,Math.min(list.length-1,pickerIndex+(event.key==='ArrowDown'?1:-1)));pickerSelected=list[pickerIndex]?.id;paintPicker();document.getElementById('option-'+pickerIndex)?.scrollIntoView({block:'nearest'});}event.preventDefault();}
 if(event.key==='Tab'&&$('.modal')){const nodes=[...$('.modal').querySelectorAll('button,input,select,textarea,a[href],[tabindex="0"]')].filter(e=>!e.disabled&&e.type!=='hidden'&&e.getClientRects().length);if(event.shiftKey&&document.activeElement===nodes[0]){nodes.at(-1)?.focus();event.preventDefault();}else if(!event.shiftKey&&document.activeElement===nodes.at(-1)){nodes[0]?.focus();event.preventDefault();}}
});
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(next!==page)navigate(next);});
window.addEventListener('beforeunload',event=>{if(!needsOnboarding(state)&&(dirty($('#main'))||dirty($('#modal-root')))){event.preventDefault();event.returnValue='还有未保存输入';}});
function clockCheck(){if(blocked())return;try{const c=evaluatePlan(state,{command:{type:'tick'}}).state;if(JSON.stringify(c)!==JSON.stringify(state)&&save(c))render();}catch(e){toast('自动顺延未保存：'+e.message);}}
setInterval(()=>{if(!blocked()&&timer?.running&&remainingSeconds()<=0)finishTimer(true);updateTimerDisplay();if(lastDate!==today()){lastDate=today();clockCheck();}},500);
window.addEventListener('focus',clockCheck);document.addEventListener('visibilitychange',()=>{if(!document.hidden)clockCheck();});
clockCheck();navigate(location.hash.slice(1)||'dashboard');
function persistTimer(){try{if(timer)localStorage.setItem(TIMER_KEY,JSON.stringify(timer));else localStorage.removeItem(TIMER_KEY);}catch{toast('计时记录暂时无法保存，请保持窗口开启。');}}
function remainingSeconds(){return timer?Math.min(timer.duration,Math.max(0,timer.running?Math.ceil((timer.until-Date.now())/1000):timer.remaining)):focusDuration*60;}
